project_name: bake

release:
  github:
    owner: breadtubetv
    name: bake

before:
  hooks:
    - go mod download

builds:
  - binary: bake
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format: tar.gz
  wrap_in_directory: true
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE
    - README.md

checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'

snapshot:
  name_template: SNAPSHOT-{{.Commit}}

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - README
    - Merge branch