environment: &environment
  environment:
    PROJECT_NAME: bake
    GO111MODULE: "on"

build_defaults: &build_defaults
  working_directory: /tmp/build
  docker:
    - image: golang:1.12.5
  <<: *environment

lint_defaults: &lint_defaults
  working_directory: /tmp/build
  docker:
    - image: golangci/golangci-lint:v1.16
  <<: *environment

version: 2.1
jobs:
  lint:
    <<: *lint_defaults
    steps:
      - checkout
      - run: golangci-lint run --config=$CIRCLE_WORKING_DIRECTORY/.golangci.yml

  test:
    <<: *build_defaults
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}-test
      - run: mkdir -p $TEST_RESULTS
      - run: "go get -u gotest.tools/gotestsum"
      - run: "gotestsum --junitfile $TEST_RESULTS/unit-tests.xml"
      - run: "go mod tidy"
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}-test
          paths:
            - "/go/pkg/mod"
      - store_test_results:
          path: /tmp/test-results

  build:
    <<: *build_defaults
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run: "GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build ."
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

workflows:
  lint_and_build:
    jobs:
      - lint
      - test
      - build:
          requires:
            - test
